### ISSUE TITLE
Voice > Connect an inbound call

### ISSUE THREAD

**Issue by adambutler** [nexmo-community/nexmo-java-quickstart#28]
See gist: https://gist.github.com/adambutler/03b42f54dd755dfd70034325a68cd9d3

**Comment by judy2k** [comment]
https://gist.github.com/judy2k/f7af158f6c6b50c5d3722428d5f87382

**Comment by leggetter** [comment]
I'd recommend we use GET for answer URL and POST for event URL (not shown here). These are the defaults and a developer would have to explicitly set things up to be different. Going with these defaults also simplifies the code.
